# These are supported funding model platforms
You want to pay me ? here is my email you can send me money via interact or any other paying system.
if I received money I will buy a coffee and I will think to you.

custom: ['leonlatour@yahoo.com']
